version: '3'

services:
  teleport:
    hostname: teleport.canvas-playground.site
    image: quay.io/gravitational/teleport:10.1.4
    container_name: teleport
    restart: unless-stopped
    ports:
      - 3023:3023
      - 3024:3024
      - 3025:3025
      - 3026:3026
      - 3080:3080
    volumes:
      - ~/teleport/config:/etc/teleport
      - ~/teleport/data:/var/lib/teleport
      - ~/teleport/ssl:/opt
      - ~/teleport/rbac:/mnt